name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: tree-sitter/parser-setup-action@v1.1
        with:
          node-version: ${{vars.NODE_VERSION}}
      - uses: tree-sitter/parser-test-action@v1.2
        with:
          test-library: true
